DECLARE EXTERNAL FUNCTION MD5
    CSTRING(4096) CHARACTER SET UTF8 NULL
    RETURNS VARCHAR(16) CHARACTER SET OCTETS FREE_IT
    ENTRY_POINT 'md5' MODULE_NAME 'fpc_udf';

DECLARE EXTERNAL FUNCTION BIN_TO_HEX
    VARCHAR(2048) CHARACTER SET OCTETS NULL
    RETURNS CSTRING(4096) CHARACTER SET ASCII FREE_IT
    ENTRY_POINT 'bin_to_hex' MODULE_NAME 'fpc_udf';

DECLARE EXTERNAL FUNCTION HEX_TO_BIN
    CSTRING(4096) CHARACTER SET ASCII NULL
    RETURNS VARCHAR(2048) CHARACTER SET OCTETS FREE_IT
    ENTRY_POINT 'hex_to_bin' MODULE_NAME 'fpc_udf';

DECLARE EXTERNAL FUNCTION FILE_IS_READABLE
    CSTRING(2048) CHARACTER SET OCTETS NULL
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'file_is_readable' MODULE_NAME 'fpc_udf';

COMMENT ON EXTERNAL FUNCTION FILE_IS_READABLE IS
'ATTN: security-compromising function';

