DECLARE EXTERNAL FUNCTION TEST_INT
    INTEGER,
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'test_int' MODULE_NAME 'fpc_udf';

DECLARE EXTERNAL FUNCTION TEST_DOUBLE
    DOUBLE PRECISION,
    DOUBLE PRECISION
    RETURNS DOUBLE PRECISION BY VALUE
    ENTRY_POINT 'test_double' MODULE_NAME 'fpc_udf';

DECLARE EXTERNAL FUNCTION TEST_FREEIT
    CSTRING(200) CHARACTER SET ASCII NULL,
    CSTRING(200) CHARACTER SET ASCII NULL
    RETURNS CSTRING(400) CHARACTER SET ASCII FREE_IT
    ENTRY_POINT 'test_freeit' MODULE_NAME 'fpc_udf';

DECLARE EXTERNAL FUNCTION TEST_RETPARAM
    VARCHAR(2000) CHARACTER SET UTF8,
    VARCHAR(2000) CHARACTER SET UTF8
    RETURNS PARAMETER 1
    ENTRY_POINT 'test_retparam' MODULE_NAME 'fpc_udf';

DECLARE EXTERNAL FUNCTION TEST_PARAMDSC
    INTEGER BY DESCRIPTOR,
    INTEGER BY DESCRIPTOR
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'test_paramdsc' MODULE_NAME 'fpc_udf';

